version: "2.0"

services:
  elastic-stack:
    build:
      context: .
      args:
        ELASTIC_S3_BACKUP_REGION: ${ELASTIC_S3_BACKUP_REGION}
        ELASTIC_S3_BACKUP_BUCKET: ${ELASTIC_S3_BACKUP_BUCKET}
        ELASTIC_S3_BACKUP_SECRET_KEY: ${ELASTIC_S3_BACKUP_SECRET_KEY}
        ELASTIC_S3_BACKUP_ACCESS_KEY: ${ELASTIC_S3_BACKUP_ACCESS_KEY}
    restart: always
    ports:
      - "${KIBANA_PORT}:5601"
      - "${ELASTIC_SEARCH_REST_API_PORT}:9200"
      - "${ELASTIC_SEARCH_JAVA_API_PORT}:9300"
      - "${LOGSTASH_PORT}:5044"
    volumes:
      - "./conf/logstash/conf.d/logstash.conf:/etc/logstash/conf.d/logstash.conf"
      - "./conf/logstash/patterns:/etc/logstash/patterns"
      - "./conf/logstash/templates:/etc/logstash/templates"
      - "./data:/var/lib/elacticsearch"
      - "./logs/elasticsearch:/var/log/elasticsearch"
      - "./logs/kibana:/var/log/kibana"
      - "./logs/logstash:/var/log/logstash"
      - "./logs/elasticsearch-backup:/var/log/elasticsearch-backup"
    tty: true